### ISSUE TITLE
Photo upload issue with Safari

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#362]
A user reports an error causing upload to fail
![brave-upload-error](https://user-images.githubusercontent.com/3805254/173634070-eeb3d6f7-6da8-4822-a39c-6857ffc34379.png)

![safari-upload-error](https://user-images.githubusercontent.com/3805254/173600552-3fbfbf44-4ad0-48b3-9e79-16416c339c87.png)

**Comment by vnugent** [comment]
Additional log from the server:
```
parsedLambdaMessage:Object
lines:Object
level:"info"
message:"#Uploading to media server failed Error: Missing user metadata\n    at handler (/var/task/.next/server/pages/api/media/upload.js:103:23)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /var/task/.next/server/pages/api/user/me.js:77:13\n    at async Object.apiResolver (/var/task/node_modules/next/dist/server/api-utils/node.js:185:9)\n    at async NextNodeServer.runApi (/var/task/node_modules/next/dist/server/next-server.js:404:9)\n    at async Object.fn (/var/task/node_modules/next/dist/server/base-server.js:507:37)\n    at async Router.execute (/var/task/node_modules/next/dist/server/router.js:212:36)\n    at async NextNodeServer.run (/var/task/node_modules/next/dist/server/base-server.js:642:29)\n    at async NextNodeServer.handleRequest (/var/task/node_modules/next/dist/server/base-server.js:334:20)\n    at async Server.module.exports (/var/task/___next_launcher.cjs:29:9)"
timestamp:"2022-06-20T19:37:51.812Z"
parse_status:"full"
report:Object
billed_duration_ms:96
duration_ms:96
max_memory_used_mb:178
memory_size_mb:1024
request_id:"70b4f4ca-c5c7-490b-8a8a-bf95b847f755"
path:"api/media/upload"
projectId:"prj_91PY5FKTHS9JJJ7ZLYJDWvSthMzW"
proxy:Object
clientIp:"197.89.10.58"
host:"tacos.openbeta.io"
method:"POST"
path:"/api/media/upload?filename=IMG_7111-2.jpg"
referer: https://tacos.openbeta.io/u/<redated>
```

The exception is generated by this check https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/api/media/upload.ts#L26

FYI - the api handler is executed on the server side.  The check failed because the user metadata object is missing.

**Comment by vnugent** [comment]
I was able to reproduce the issue.  The bug is in the Post-Login action running on Auth0.  

An improved version https://github.com/OpenBeta/open-tacos/blob/develop/AuthProvider/postLoginAction.js

The old (buggy) version:
```
exports.onExecutePostLogin = async ({user}, api) => {
  const { v4: uuidv4 } = require('uuid')
  const { uniqueNamesGenerator, adjectives, colors, animals } = require('unique-names-generator')
  user.user_metadata.nick = user.user_metadata?.nick ?? uniqueNamesGenerator({ dictionaries: [adjectives, colors, animals] }) // big_red_donkey

  api.user.setUserMetadata('name', user.user_metadata.name || user.nickname)
  api.user.setUserMetadata('bio', user.user_metadata.bio || ' ')
  api.user.setUserMetadata('uuid', user.user_metadata.uuid || uuidv4()) // uuid is correctly generated and persisted 
  api.user.setUserMetadata('nick', user.user_metadata.nick) 

  const ns ='https://tacos.openbeta.io/'
  api.idToken.setCustomClaim(ns + "user_metadata", user.user_metadata) // Bug! this local copy of user_metadata doesn't have uuid
};

```

**Comment by vnugent** [comment]
I believe this has been fixed.
