### ISSUE TITLE
Area is shown in search bar auto-complete, but data not found

### ISSUE THREAD

**Issue by actuallyyun** [OpenBeta/open-tacos#752]
## Steps to Reproduce

1.Search _Siurana_
2.Click on the auto complete result of _Siurana_
3.Redirected to this page https://openbeta.io/crag/ab73ede7-7331-5b3a-ac26-7bfd39190257 but no results were shown.
4. I tested it again with localhost, and saw this error:
```
error - ApolloError: Area ab73ede7-7331-5b3a-ac26-7bfd39190257 not found.
    at new ApolloError (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/errors/errors.cjs:34:28)
    at /Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/core/core.cjs:1678:47
    at both (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/utilities/utilities.cjs:997:53)
    at /Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/utilities/utilities.cjs:990:72
    at new Promise (<anonymous>)
    at Object.then (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/utilities/utilities.cjs:990:24)
    at Object.next (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/utilities/utilities.cjs:998:49)
    at notifySubscription (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/zen-observable/lib/Observable.js:235:7)
    at /Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/utilities/utilities.cjs:980:68
    at Array.forEach (<anonymous>)
    at iterateObserversSafely (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/utilities/utilities.cjs:980:25)
    at Object.next (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/utilities/utilities.cjs:1072:21)
    at notifySubscription (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/zen-observable/lib/Observable.js:135:18)
    at onNotify (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/zen-observable/lib/Observable.js:179:3)
    at SubscriptionObserver.next (/Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/zen-observable/lib/Observable.js:235:7)
    at /Users/Ayun/webDev/ContributingOS/open-tacos/node_modules/@apollo/client/link/http/http.cjs:302:70
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  graphQLErrors: [
    {
      message: 'Area ab73ede7-7331-5b3a-ac26-7bfd39190257 not found.',
      locations: [Array],
      path: [Array],
      extensions: [Object]
    }
  ],
  clientErrors: [],
  networkError: null,
  extraInfo: undefined,
  page: '/crag/[id]'
}
```

**Comment by theavitw** [comment]
Hey, @actuallyyun 
Can I try t work on this?

**Comment by vnugent** [comment]
@theavitw @actuallyyun we have 2 separate environments, production and staging in which the data are slightly different.   
However, due to cost we only have 1 search service used by both production & staging.  In this case the area exists in production but not in staging (where your local development env connects to).

Long term solution:  periodically copy prod data to staging.  I want to improve the developer experience and make it less confusion.  Do you have any suggestions?

**Comment by theavitw** [comment]
I Think It would be great.

**Comment by theavitw** [comment]
Is this project for donation?
Or this is NGO

**Comment by actuallyyun** [comment]
> Hey, @actuallyyun Can I try t work on this?

Go for it!

**Comment by actuallyyun** [comment]
I think there's some confusion. The behavior I reported happened in the released product.
